### ISSUE TITLE
flairs in /study - the contributor flairs are out of place

### ISSUE THREAD

**Issue by SergioGlorias** [Siderite/lichessTools#592] opened 2024-05-14 20:39 UTC
![Screenshot 2024-05-14 21 30 55](https://github.com/Siderite/lichessTools/assets/9739913/6583834b-3e6c-4c2a-ad86-f4adfde147f7)

**Comment by Siderite** [comment] 2024-05-15 05:03
What seems to be the problem?

**Comment by SergioGlorias** [comment] 2024-05-15 06:03
I refer to the flairs of the contributors
I think they are a little out of place

**Comment by Siderite** [comment] 2024-05-15 07:06
They are shifted to the right a bit by design (which I know nothing about :D ) If you have a suggestion on how to place them better, please tell me. Thanks!

**Comment by Siderite** [comment] 2024-05-15 08:10
Fixed in v2.3.78

**Closed** 2024-05-16 07:21 UTC
Labels: enhancement
