### ISSUE TITLE
Better Board Image export remains broken after update

### ISSUE THREAD

**Issue by akafncll** [Siderite/lichessTools#671] opened 2024-07-03 03:11 UTC
Greetings! I chatted with you on Discord about this problem, but even after the update today I cannot export the "Better" board images. The behavior remains the same: 

- Clicking the Screenshot link with the Analysis Board or Board Editor (or the Board button in a study) does nothing. 

- Right-clicking and opening in a new tab from the Analysis Board always opens an image of the start position with default lichess colors and pieces.

- Right-clicking and opening in a new tab from the Board Editor shows the correct position on the default lichess board and colors.

- Right-clicking and opening in a new tab from a Study shows the correct position, board and pieces, but no arrows or anything else.

I have tried removing and reinstalling the extension and resetting all settings and enabling only the Better Board Image option.

I even tried with a new Chrome profile, all default, and only the LiChess Tools extension, but same behavior.

I have verified I am running version 2.3.103 of the extension.

I am running Chrome 126.0.6478.127 (Official Build) (arm64) on OSX Sonoma 14.5

Incidentally, I tested in Arc, a different Chromium browser, and experience the same issue. I am beginning to wonder if I am misunderstanding what I should be seeing!

Please let me know how I can help troubleshoot...THANKS!

**Comment by Siderite** [comment] 2024-07-03 07:03
I can't reproduce it. For me it works fine. Do you have any errors in the console of the browser's Developer Tools?

**Comment by Siderite** [comment] 2024-07-03 19:20
Finally fixed in v2.3.105. The theme name does not equate with a clear image URL, have to take it from the board itself.

**Closed by Siderite** 2024-07-03 19:20 UTC
Labels: bug
